cmake_minimum_required(VERSION 3.16)
project(VTQuiz LANGUAGES C CXX)




set(CMAKE_CXX_STANDARD 17)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O3")
set(CMAKE_EXE_LINKER_FLAGS "-static")

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/output")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/output")


set(BUILD_SHARED_LIBS OFF CACHE BOOL "Build everything static" FORCE)


set(CMAKE_PREFIX_PATH "${CMAKE_SOURCE_DIR}/vendored" CACHE PATH "Vendored libs path")


set(SDL_SHARED OFF CACHE BOOL "" FORCE)
set(SDLTTF_PLUTOSVG OFF CACHE BOOL "" FORCE)
set(SDLIMAGE_AVIF OFF CACHE BOOL "" FORCE)
set(SDLIMAGE_BMP OFF CACHE BOOL "" FORCE)
set(SDLIMAGE_JPEG OFF CACHE BOOL "" FORCE)
set(SDLIMAGE_WEBP OFF CACHE BOOL "" FORCE)


add_subdirectory(vendored/SDL EXCLUDE_FROM_ALL)
add_subdirectory(vendored/SDL3_image EXCLUDE_FROM_ALL)
add_subdirectory(vendored/SDL3_ttf EXCLUDE_FROM_ALL)
add_subdirectory(src)